### ISSUE TITLE
Failed to Install.

### ISSUE THREAD

**Issue by garrisonz** [PardisTaghavi/SwinMTL#1]
Thanks for your great work. It look like interesting!

```
$ conda env create --file environment.yml

...
Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.6,<3.7; 0.1.1 Requires-Python >=3.6,<3.7; 0.1.2 Requires-Python >=3.6,<3.7; 0.1.3 Requires-Python >=3.6,<3.7; 0.1.4 Requires-Python >=3.6,<3.7; 0.1.5 Requires-Python >=3.6,<3.7; 0.1.6 Requires-Python >=3.6,<3.7; 2.10.1 Requires-Python <3; 2.11.0 Requires-Python <3; 2.11.1 Requires-Python <3; 2.4.0 Requires-Python <3; 2.4.1 Requires-Python <3; 2.4.2 Requires-Python <3; 2.4.3 Requires-Python <3; 2.4.4 Requires-Python <3; 2.5.0 Requires-Python <3; 2.5.1 Requires-Python <3; 2.5.2 Requires-Python <3; 2.6.0 Requires-Python <3; 2.6.1 Requires-Python <3; 2.6.2 Requires-Python <3; 2.7.0 Requires-Python <3; 2.7.2 Requires-Python <3; 2.8.0 Requires-Python <3; 2.8.1 Requires-Python <3; 2.8.2 Requires-Python <3; 2.8.3 Requires-Python <3; 2.8.4 Requires-Python <3; 2.8.5 Requires-Python <3; 2.8.6 Requires-Python <3; 2.8.7 Requires-Python <3; 2.9.2 Requires-Python <3
ERROR: Could not find a version that satisfies the requirement azfuse==0.1 (from versions: none)
ERROR: No matching distribution found for azfuse==0.1 failed

CondaEnvException: Pip failed
```

To Install azfuse by pip manaully will cause other version conflict error.

The dependecies is too long to handle conflict manully.
Can you provide the dependencies more concise dependencies? Thanks

**Comment by ParimiHarsha** [comment]
Hi garrisonz,

Thank you for raising this issue and bringing it to our attention. We appreciate your feedback and apologize for any inconvenience caused.

I'm glad to inform you that the issue has been addressed with the recent #3  pull request. We've made the necessary adjustments to the dependencies to ensure compatibility and resolve the conflict you encountered.

Could you please try again with the latest changes and let us know if the issue still persists? Your feedback is valuable to us, and we're here to assist you further if needed.

Thank you once again for your contribution and patience.

Best regards,
Parimi
